Update Jnkinsfile2

diff --git a/Jnkinsfile2 b/Jnkinsfile2
--- a/Jnkinsfile2
+++ b/Jnkinsfile2
@@ -43,9 +43,15 @@ pipeline {
             steps {
                 echo "Deploying WAR file using curl..."
                 sh """
-                    curl -u sai:dd \
-                    --upload-file /var/lib/jenkins/workspace/WQ/target/maven-web-application.war \
-                    "http://13.235.243.213:8080/manager/text/deploy?path=/maven-web-application&update=true"
+                    set -e
+                    WAR_FILE=/var/lib/jenkins/workspace/WQ/target/maven-web-application.war
+                    if [ ! -f \$WAR_FILE ]; then
+                        echo "WAR file not found!"
+                        exit 1
+                    fi
+                    curl -v -u sai:dd \
+                        --upload-file \$WAR_FILE \
+                        "http://13.235.243.213:8080/manager/text/deploy?path=/maven-web-application&update=true"
                 """
             }
         }
